-- Add these two tables to your existing schema.sql

-- Extended Anomalies table (add columns to existing if needed)
ALTER TABLE Anomalies ADD COLUMN qrs INTEGER;
ALTER TABLE Anomalies ADD COLUMN pqc_label TEXT;
ALTER TABLE Anomalies ADD COLUMN verdict_label TEXT;
ALTER TABLE Anomalies ADD COLUMN confidence REAL;

-- New PQC session tracking table
CREATE TABLE IF NOT EXISTS pqc_sessions (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    src_ip             TEXT,
    dst_ip             TEXT,
    tls_version        TEXT,
    cipher_suite       TEXT,
    kex_algo           TEXT,
    cert_key_bits      INTEGER,
    qrs                INTEGER,
    label              TEXT,
    has_pqc_extension  INTEGER DEFAULT 0,
    ts                 DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pqc_qrs ON pqc_sessions(qrs);
CREATE INDEX IF NOT EXISTS idx_pqc_ts  ON pqc_sessions(ts);
```

---

## Your project structure going forward
```
your-project/
├── nids1.py                  ← replaced (above)
├── preprocessing.py          ← new
├── ensemble.py               ← new
├── pqc_extractor.py          ← new
├── pqc_risk_scorer.py        ← new
├── train_and_save_all.py     ← new (run this first!)
├── models/
│   ├── loader.py             ← new
│   ├── random_forest.pkl     ← generated by train_and_save_all.py
│   ├── xgboost.pkl
│   ├── logistic_regression.pkl
│   ├── knn.pkl
│   ├── svm.pkl
│   ├── isolation_forest.pkl
│   ├── autoencoder.h5
│   ├── autoencoder_meta.pkl
│   ├── scaler.pkl
│   ├── label_encoder.pkl
│   └── ja3_encoders.pkl
└── schema.sql                ← add the ALTER TABLE statements